### PR TITLE
fix: add link to info about format of version number

### PR DESCRIPTION
**Pull request by jshackell-sfdc**
### What does this PR do?

Adds a small description for --version-number flag with link to Dev Guide topic about the format of the version number. This fixes a Dev Doc Feedback bug that came in from a customer. 

### What issues does this PR fix or reference?
@W-14131476@

### CODE REVIEW

**Comment by penelopy** [comment]
Seeing this in context on the package create command, makes me reethink this a bit. The version number isn't specified when you run the command, it is one of many things you specified in the sfdx-project.json file. So instead of calling out the version number, which feels arbitrary, let's say:

The settings in the sfdx-project.json file create an outline for your package. For more information about these settings and how to specify them, see https://developer.salesforce.com/docs/atlas.en-us.pkg2_dev.meta/pkg2_dev/sfdx_dev2gp_config_file.htm.

**Comment by jshackell-sfdc** [comment]
Hmmm, I'm a bit confused.  The command has this flag:

  -n, --version-number=<value>       Version number of the package version to be created; overrides the sfdx-project.json value.

So

**Comment by jshackell-sfdc** [comment]
A couple of clarifications:

* this update is for "package version create" not "package create"
* I'm updating the description (not the summary) of the --version-number flag, which (according to the help!) you use to override the value in the sfdx-project.json file.  So the blurb doesn't show up in the command description, but later in the flag description.

Just wanted to make sure you know the context!

**Comment by penelopy** [comment]
In that case, carry on as you proposed! Thanks for clarifying.

**Review by shetzel — APPROVED** [review]

**Pull request merged**
